Feature/account
iobit-pt/comercio-vizinho-beckend pull request #2
Opened 2024-08-07 15:48 UTC by wesAlves

2024-08-08 19:34 UTC, bruflor requested changes

2024-08-08 19:34 UTC, bruflor commented on comercio_vizinho_be/src/main/java/com/iobit/comercio_vizinho_be/entities/Address.java
> +    private String build;
Sei que ainda não definimos padrão de nomeação pro projeto, mas creio que esses nomes de variáveis não estão claros do que seria. Por exemplo, o que é build em um endereço? Eu não vejo esse tipo de aplicação e a primeira instancia me soa muito estranho. Acredito que no "num" também poderiamos usar a palavra por completo ou a designação dela, como "number", ou até "streetNumber" para ficar mesmo mais fácil de entender.

2024-08-08 19:34 UTC, bruflor commented on comercio_vizinho_be/src/main/resources/application-dev.properties
Esse ficheiro é a mesma coisa que comentei no outro PR, acredito que ele não venha com passowrd e secrets explicitos pro github

2024-08-12 10:07 UTC, wesAlves commented on comercio_vizinho_be/src/main/resources/application-dev.properties
Não sei o que foi comentado no outro. Aqui pode já fazer parte de um ficheiro .env, porém não faz diferença uma vez que é apenas o ambiente local não expoem nada

2024-08-13 18:55 UTC, bruflor approved these changes

2024-08-13 19:06 UTC, bruflor approved these changes

2024-08-13 19:06 UTC, bruflor approved these changes

2024-08-13 19:07 UTC, bruflor approved these changes

2024-08-13 19:09 UTC, bruflor approved these changes

2024-08-13 19:13 UTC, bruflor approved these changes

2024-08-13 19:15 UTC, closed without merging